import React, { FC, ReactNode } from "react";

import './globals.css'
import 'primereact/resources/themes/saga-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import AppHeader from "@components/AppHeader";
import AppMenu from "@components/AppMenu";
import AppFooter from "@components/AppFooter";

import {
  LayoutWrapperSC,
  LayoutSidebarSC,
  LayoutMainContainerSC,
  LayoutMainSC
} from "./layout";


import StyledComponentsRegistry from "@lib/registry";
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] })



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: FC<{ children: ReactNode }> = (props) => {
  const { children } = props;


  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="favicon.svg" sizes="any" />

      </Head>
      <title>Taskbook</title>
      <body id="root">
        <StyledComponentsRegistry>
          <div className="layout-wrapper">
            <AppHeader />
            <div className="layout-sidebar">
              <AppMenu />
            </div>
            <div className="layout-main-container">
              <div className="layout-main">{children}</div>
              <AppFooter />
            </div>
            <div className="layout-mask"></div>

          </div>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
};

export default RootLayout;
